export const CATEGORY_LABELS: Record<string, string> = {
  landing: 'Landing Pages',
  business: 'Business Website',
  ecommerce: 'E-Commerce',
  app: 'Mobile Application',
  seo: 'SEO Services',
  service: 'Services',
  custom: 'Custom Solution',
  subscription: 'Subscription',
  digital: 'Digital Product',
  physical: 'Physical Product',
  consulting: 'Consulting',
  training: 'Training',
  marketing: 'Marketing',
  design: 'Design',
  development: 'Development',
  maintenance: 'Maintenance',
  support: 'Support',
  enterprise: 'Enterprise',
  startup: 'Startup',
  personal: 'Personal',
  professional: 'Professional',
  other: 'Other'
};
